[package]
name = "quickstock_rust"
version = "0.1.0"
edition = "2021"
authors = ["Garrett Smith <your-email@example.com>"]
description = "QuickStock: Inventory and Sales Management, rewritten in Rust"
license = "MIT"

[dependencies]
bcrypt = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }
actix-web = "4"
actix-cors = "0.6"
eframe = "0.31.1"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.8"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.22"
log = "0.4"
env_logger = "0.10"
rusqlite = { version = "0.29.0", features = ["bundled"] }
csv = "1.1"

[dev-dependencies]
# For async tests
tokio = { version = "1.36", features = ["full"] }

# Include sqlx macros in tests
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls", "macros"] }

winapi = { version = "0.3.9", features = ["winuser", "windef"] }

# Included for tests
[lib]
path = "src/lib.rs"
